
[functions.create-student-login]
enabled = true
verify_jwt = false
import_map = "./functions/create-student-login/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-student-login/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-student-login/*.html" ]

[functions.reset-student-password]
enabled = true
verify_jwt = false
import_map = "./functions/reset-student-password/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/reset-student-password/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/reset-student-password/*.html" ]

[functions.update-student-login-status]
enabled = true
verify_jwt = false
import_map = "./functions/update-student-login-status/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/update-student-login-status/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/update-student-login-status/*.html" ]

[functions.record-student-login]
enabled = true
verify_jwt = false
import_map = "./functions/record-student-login/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/record-student-login/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/record-student-login/*.html" ]
