import { useEffect, useMemo, useState } from "react";
import SymbolBankShell from "../components/symbolBank/SymbolBankShell";
import SymbolGrid from "../components/symbolBank/SymbolGrid";
import { getActiveSymbolBankRecords } from "../lib/symbolBank";
import { getPlayableProfileMembership } from "../lib/membership";
import { isPaidMembership } from "../lib/membershipAccess";

export default function SymbolBankVault() {
  const [release,setRelease]=useState(null), [records,setRecords]=useState([]), [query,setQuery]=useState(""), [level,setLevel]=useState("all"), [memberAccess,setMemberAccess]=useState(false), [error,setError]=useState("");
  useEffect(()=>{let live=true; Promise.all([getActiveSymbolBankRecords(),getPlayableProfileMembership()]).then(([bank,access])=>{if(live){setRelease(bank.release);setRecords(bank.records);setMemberAccess(isPaidMembership(access.membership));}}).catch(e=>live&&setError(e?.message||"Could not load vault.")); return()=>{live=false};},[]);
  const filtered=useMemo(()=>{const q=query.toLowerCase().trim(); return records.filter(r=>(level==="all"||r.level===Number(level))&&(!q||[r.display,r.canonical_name,r.short_meaning,r.symbol_class,...(Array.isArray(r.read_as)?r.read_as:[])].filter(Boolean).join(" ").toLowerCase().includes(q)));},[records,query,level]);
  return <SymbolBankShell><section className="mb-6 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><p className="text-xs font-black uppercase tracking-[.2em] text-blue-600">The Vault</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Mathematics Symbol Bank</h1><p className="mt-3 text-slate-600">{release ? `${records.length} published records · active release ${release.symbol_bank_version}` : "Loading active release…"}</p><div className="mt-6 grid gap-4"><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search symbol, name, meaning or read-as..." className="w-full rounded-2xl border border-slate-300 px-4 py-3 outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-100"/><div className="flex gap-2 overflow-x-auto">{[["all","All"],["1","Level 1"],["2","Level 2"],["3","Level 3"]].map(([key,label])=><button key={key} onClick={()=>setLevel(key)} className={level===key?"rounded-full bg-blue-600 px-4 py-2 text-sm font-black text-white":"rounded-full border border-slate-200 bg-white px-4 py-2 text-sm font-black text-slate-700"}>{label}</button>)}</div></div></section>{error ? <div className="rounded-2xl border border-red-200 bg-red-50 p-8 text-red-800">{error}</div> : <><p className="mb-4 text-sm font-bold text-slate-600">Showing {filtered.length} of {records.length} · {memberAccess?"Member Vault open":"30 free · 62 member"}</p><SymbolGrid records={filtered} memberAccess={memberAccess}/></>}</SymbolBankShell>;
}
