import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import SymbolBankShell from "../components/symbolBank/SymbolBankShell";
import { getActiveSymbolBankRecords } from "../lib/symbolBank";

export default function SymbolBankHome() {
  const [release,setRelease]=useState(null); const [records,setRecords]=useState([]); const [error,setError]=useState("");
  useEffect(()=>{ let live=true; getActiveSymbolBankRecords().then(({release,records})=>{if(live){setRelease(release);setRecords(records);}}).catch(e=>live&&setError(e?.message||"Could not load Symbol Bank.")); return()=>{live=false};},[]);
  const counts=useMemo(()=>({total:records.length,free:records.filter(r=>r.access_tier==="free").length,member:records.filter(r=>r.access_tier==="member").length}),[records]);
  return <SymbolBankShell>{error ? <div className="rounded-3xl border border-red-200 bg-red-50 p-8 text-red-800">{error}</div> : <><section className="overflow-hidden rounded-3xl bg-slate-950 p-6 text-white shadow-xl sm:p-10"><p className="text-xs font-black uppercase tracking-[.2em] text-yellow-300">CountMeInTT Mathematics</p><h1 className="mt-3 text-4xl font-black sm:text-5xl">Mathematics Symbol Bank</h1><p className="mt-4 text-lg font-semibold text-slate-200">Know the symbols. Read the mathematics.</p><p className="mt-4 max-w-2xl text-slate-300">{release ? `${counts.total} mathematical symbols and notation structures from SEA to CSEC · ${counts.free} free · ${counts.member} member-only.` : "Loading the active published Symbol Bank release…"}</p><Link to="/symbol-bank/vault" className="mt-7 inline-flex rounded-xl bg-yellow-400 px-6 py-3 font-black text-slate-950">Enter the Vault</Link></section>{release && <section className="mt-6 grid gap-4 md:grid-cols-3">{[[1,"Primary / SEA"],[2,"Forms 1–3"],[3,"CSEC"]].map(([level,label])=><article key={level} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-black uppercase tracking-wide text-blue-600">Vault {level}</p><h2 className="mt-2 text-2xl font-black">{label}</h2><p className="mt-4 text-3xl font-black">{records.filter(r=>r.level===level).length}{level>1?" new":""}</p><p className="mt-1 text-sm font-semibold text-slate-500">{records.filter(r=>r.level===level&&r.access_tier==="free").length} free</p></article>)}</section>}</>}</SymbolBankShell>;
}
