export const NUMBERVERSE_ACTIONS = Object.freeze({
  START: "start",
  SUBMIT: "submit",
});

export const NUMBERVERSE_COMPLETION_STATUSES = Object.freeze({
  COMPLETE_SUCCESS: "COMPLETE_SUCCESS",
  PARTIAL_SUCCESS: "PARTIAL_SUCCESS",
  UNSUCCESSFUL: "UNSUCCESSFUL",
  INVALID_RESPONSE: "INVALID_RESPONSE",
  NO_RESPONSE: "NO_RESPONSE",
});

export const NUMBERVERSE_INDEPENDENCE_STATES = Object.freeze({
  INDEPENDENT: "INDEPENDENT",
  RETRIED: "RETRIED",
  SCAFFOLDED: "SCAFFOLDED",
  ASSISTED: "ASSISTED",
  REVEALED: "REVEALED",
});

export const NUMBERVERSE_TEMPLATES = Object.freeze({
  FACTOR_COMPLETE_PAIR: "NV_FACTOR_COMPLETE_PAIR",
});


